version: '3'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: postgres-2dots1line
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=2dots1line
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 2dots1line

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.9.0
    container_name: neo4j-2dots1line
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - 2dots1line
      
  # Weaviate Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.22.5
    container_name: weaviate-2dots1line
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - 2dots1line

networks:
  2dots1line:

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  weaviate_data:

# Note: Ensure Docker Desktop (or equivalent) is running with sufficient memory allocated. 